### ISSUE TITLE
Please Release New Gem to Support...

### ISSUE THREAD

**Issue by ninp0** [didww/credit_card_validations#108]
ruby-3.0.3 && (
  activerecord >= 6.3 ||
  activerecord 7.0
)

_/\_

**Comment by jnwaletzko** [comment]
+1

**Comment by ninp0** [comment]
Looks like this is happening as a result of:

https://github.com/didww/credit_card_validations/blob/master/credit_card_validations.gemspec#L28-L29 

Support version ">= 7.0.2.2"  instead of "<= 6.2"

**Comment by jnwaletzko** [comment]
Yeah, it would be awesome to get this merged https://github.com/didww/credit_card_validations/pull/109

**Comment by ninp0** [comment]
Just submitted pull request https://github.com/didww/credit_card_validations/pull/111

**Comment by danigirl329** [comment]
Thanks @ninp0! I ran into this issue last year when I wanted to upgrade past 6.1 and was having issues with this as well.  Hoping this could be an expedited change!! We are starting to work on upgrading to Rails 7.

**Comment by ninp0** [comment]
Looks like credit_card_validations 5.0.0 addresses this issue.  Thanks @Fivell
