### ISSUE TITLE
Discover test card issue

### ISSUE THREAD

**Issue by jmortlock** [didww/credit_card_validations#110]
Hi

Since the updates to the discover rules a common card number used for testing scenarios is no longer detected. 
Card Number is: 6011 1111 1111 1117

This card number is used in many payment providers as one of two example discover cards to use for testing.
for example https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm

**Comment by Fivell** [comment]
@jmortlock there was update merged because of https://www.discoverglobalnetwork.com/content/dam/discover/en_us/dgn/pdfs/IPP-VAR-Enabler-Compliance.pdf

seems 60111 is no longer actual

**Comment by Fivell** [comment]
related to https://github.com/didww/credit_card_validations/commit/9a44f37a1f9462469b964b582d64c6a13bef2eac

**Comment by state-developer** [comment]
For anyone looking for a solution, my solution was to fork the code and add it back into the prefixes.

**Comment by Fivell** [comment]
fixed by allowing to override credit card rules with own file 
https://github.com/didww/credit_card_validations#configuration
